# https://taskfile.dev
version: '3'

vars:
  BINFILE: k8see-webui
  IMG: sgaunet/k8see-webui:latest

tasks:
  default:
    dir: src
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  image:
    deps: 
    - default
    sources:
      - ./{{.BINFILE}}
      - Dockerfile
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    dir: src
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist --snapshot
    
  release:
    dir: src
    cmds:
      - GITLAB_TOKEN="" goreleaser --rm-dist